const errorMap = {
  INVALID_FIELDS: 400,
  INVALID_VALUE: 400,
  FIELDS_MISSING: 400,
  JWT_MALFORMED: 401,
  MISSING_AUTH_TOKEN: 401,
  USER_NOT_FOUND: 404,
  USER_ALREADY_EXISTS: 409,
  CATEGORY_NOT_FOUND: 400,
  CATEGORY_ALREADY_EXISTS: 409,
  POST_NOT_FOUND: 404,
  UNAUTHORIZED_USER: 401,
};

const mapError = (type) => errorMap[type] || 500;

module.exports = {
  errorMap,
  mapError,
};
